package com.demonicmusichost.app.ui.scanner

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.demonicmusichost.app.R
import com.google.zxing.integration.android.IntentIntegrator
import com.google.zxing.integration.android.IntentResult

/**
 * Launches the ZXing QR-code scanner and returns the scanned session code
 * (e.g. "DMH-ABC123") via [EXTRA_RESULT_CODE].
 *
 * The QR codes generated by the DMH server encode a URL like:
 *   https://yourserver.com/?code=DMH-ABC123
 * This activity extracts just the session code from that URL and passes it back.
 */
class QRScannerActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        IntentIntegrator(this).apply {
            setPrompt(getString(R.string.qr_scan_prompt))
            setBeepEnabled(true)
            setOrientationLocked(true)
            setBarcodeImageEnabled(false)
            captureActivity = com.journeyapps.barcodescanner.CaptureActivity::class.java
        }.initiateScan()
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        val result: IntentResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, data)

        if (result.contents == null) {
            // User cancelled
            setResult(RESULT_CANCELED)
            finish()
            return
        }

        val scanned = result.contents.trim()
        val sessionCode = extractSessionCode(scanned)

        if (sessionCode == null) {
            Toast.makeText(this, getString(R.string.qr_invalid), Toast.LENGTH_SHORT).show()
            setResult(RESULT_CANCELED)
            finish()
            return
        }

        val intent = Intent().putExtra(EXTRA_RESULT_CODE, sessionCode)
        setResult(RESULT_OK, intent)
        finish()
    }

    /**
     * Extracts "DMH-XXXXXX" from either a raw code string or a URL like
     * "https://server.com/?code=DMH-XXXXXX".
     */
    private fun extractSessionCode(raw: String): String? {
        // Direct code match: e.g. "DMH-ABC123"
        val directMatch = Regex("^DMH-[A-Z0-9]{6}$").find(raw.uppercase())
        if (directMatch != null) return directMatch.value

        // URL with ?code= param
        return try {
            val uri = android.net.Uri.parse(raw)
            val code = uri.getQueryParameter("code")
            if (!code.isNullOrBlank() && code.uppercase().matches(Regex("DMH-[A-Z0-9]{6}"))) {
                code.uppercase()
            } else null
        } catch (e: Exception) {
            null
        }
    }

    companion object {
        const val EXTRA_RESULT_CODE = "extra_session_code"
    }
}
